FORCE_EVAL:
  METHOD: Quickstep
  DFT:
    BASIS_SET_FILE_NAME: BASIS_MOLOPT
    POTENTIAL_FILE_NAME: GTH_POTENTIALS
    UKS: .TRUE.
    CHARGE: 1
    POISSON:
      PERIODIC: NONE
      POISSON_SOLVER: MT
    SCF:
      SCF_GUESS: RESTART
      EPS_SCF: 1e-6
      MAX_SCF: 300
    XC:
      XC_FUNCTIONAL:
        _: PBE
      VDW_POTENTIAL: 
        DISPERSION_FUNCTIONAL: PAIR_POTENTIAL
        PAIR_POTENTIAL:
          TYPE: DFTD3
          PARAMETER_FILE_NAME: dftd3.dat
          REFERENCE_FUNCTIONAL: PBE
